// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type House struct {
	ID      string   `json:"id"`
	Address string   `json:"address"`
	State   string   `json:"state"`
	Leases  []*Lease `json:"leases"`
}

type Lease struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type NewHouse struct {
	Address string   `json:"address"`
	State   string   `json:"state"`
	Leases  []string `json:"leases"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
